apiVersion: apps/v1
kind: Deployment
metadata:
  name: rickandmorty
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rickandmorty
  template:
    metadata:
      labels:
        app: rickandmorty
    spec:
      containers:
        - name: rickandmorty
          image: zagadatpro10/rickandmorty:latest
          ports:
            - containerPort: 3000
# zagadatpro10/rickandmorty:latest is the image that we pushed to Docker Hub
